apiVersion: apps/v1
kind: Deployment
metadata:
  name: practica-02-deployment-multibranch
  namespace: staging
spec:
  selector:
   matchLabels:
    app: practica-02-jenkins
  replicas: 1
  template:
    metadata:
      labels:
        app: practica-02-jenkins
    spec:
      containers:
        - name: practica-02-jenkins
          image: 'aldavid/practica-demo-staging:8'
          ports:
            - containerPort: 8080
              name: practica-01port
          imagePullPolicy: Always
          env:
          - name: nombre
            value: "David"

---
kind: Service
apiVersion: v1
metadata:
  name: practica-02-jenkins-service
  namespace: staging
  labels:
    app: practica-02-jenkins
spec:   
  ports:
  - name: practica-02-jenkins
    port: 8080
    nodePort : 31898
  #type: LoadBalancer-
  type: NodePort
  selector:
   app: practica-02-jenkins
